apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 4
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world 
        image: gcr.io/hit-and-try/gke-auto:2.0.0
        imagePullPolicy: Always
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0%
